name: izakaya_navi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.1.0
  envied: ^0.3.0+3
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.1
  flutter_dotenv: ^5.1.0
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  envied_generator: ^0.3.0+3
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - .env

